export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS' 
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const TYPE_INPUT = "TYPE_INPUT"
export const CANCEL_BUTTON = "CANCEL_BUTTON"

